import classnames from 'classnames'

const iconOptions = (p) => ({
  'fa-stack-1x': p.stack === '1',
  'fa-stack-2x': p.stack === '2',
  'fa-lg': p.size === '1',
  'fa-2x': p.size === '2',
  'fa-3x': p.size === '3',
  'fa-4x': p.size === '4',
  'fa-5x': p.size === '5',
  'fa-inverse': p.inverse,
  'fa-fw': p.fw,
  'fa-li': p.li,
  'fa-spin': p.spin,
  'fa-pulse': p.pulse,
  'fa-border': p.border,
  'fa-flip-horizontal': p.flip === 'horizontal',
  'fa-flip-vertical': p.flip === 'vertical',
  'fa-pull-right': p.pull === 'right',
  'fa-pull-left': p.pull === 'left',
  'fa-rotate-90': p.rotate === '90',
  'fa-rotate-180': p.rotate === '180',
  'fa-rotate-270': p.rotate === '270',
})

export default (p) => <i className={classnames("fa fa-font-awesome", iconOptions(p), p.className)}/>
export const CaretDown = (p) => <i className={classnames("fa fa-caret-down", iconOptions(p), p.className)}/>
export const UniversalAccess = (p) => <i className={classnames("fa fa-universal-access", iconOptions(p), p.className)}/>
export const Flag = (p) => <i className={classnames("fa fa-flag", iconOptions(p), p.className)}/>
export const Search = (p) => <i className={classnames("fa fa-search", iconOptions(p), p.className)}/>
export const AddressBook = (p) => <i className={classnames("fa fa-address-book", iconOptions(p), p.className)}/>
export const AddressBookO = (p) => <i className={classnames("fa fa-address-book-o", iconOptions(p), p.className)}/>
export const AddressCard = (p) => <i className={classnames("fa fa-address-card", iconOptions(p), p.className)}/>
export const AddressCardO = (p) => <i className={classnames("fa fa-address-card-o", iconOptions(p), p.className)}/>
export const Bandcamp = (p) => <i className={classnames("fa fa-bandcamp", iconOptions(p), p.className)}/>
export const Bath = (p) => <i className={classnames("fa fa-bath", iconOptions(p), p.className)}/>
export const Bathtub = (p) => <i className={classnames("fa fa-bathtub", iconOptions(p), p.className)}/>
export const DriversLicense = (p) => <i className={classnames("fa fa-drivers-license", iconOptions(p), p.className)}/>
export const DriversLicenseO = (p) => <i className={classnames("fa fa-drivers-license-o", iconOptions(p), p.className)}/>
export const Eercast = (p) => <i className={classnames("fa fa-eercast", iconOptions(p), p.className)}/>
export const EnvelopeOpen = (p) => <i className={classnames("fa fa-envelope-open", iconOptions(p), p.className)}/>
export const EnvelopeOpenO = (p) => <i className={classnames("fa fa-envelope-open-o", iconOptions(p), p.className)}/>
export const Etsy = (p) => <i className={classnames("fa fa-etsy", iconOptions(p), p.className)}/>
export const FreeCodeCamp = (p) => <i className={classnames("fa fa-free-code-camp", iconOptions(p), p.className)}/>
export const Grav = (p) => <i className={classnames("fa fa-grav", iconOptions(p), p.className)}/>
export const HandshakeO = (p) => <i className={classnames("fa fa-handshake-o", iconOptions(p), p.className)}/>
export const HandsHelping = (p) => <i className={classnames("fa fa-hands-helping", iconOptions(p), p.className)}/>
export const IdBadge = (p) => <i className={classnames("fa fa-id-badge", iconOptions(p), p.className)}/>
export const IdCard = (p) => <i className={classnames("fa fa-id-card", iconOptions(p), p.className)}/>
export const IdCardO = (p) => <i className={classnames("fa fa-id-card-o", iconOptions(p), p.className)}/>
export const Imdb = (p) => <i className={classnames("fa fa-imdb", iconOptions(p), p.className)}/>
export const Linode = (p) => <i className={classnames("fa fa-linode", iconOptions(p), p.className)}/>
export const Meetup = (p) => <i className={classnames("fa fa-meetup", iconOptions(p), p.className)}/>
export const Microchip = (p) => <i className={classnames("fa fa-microchip", iconOptions(p), p.className)}/>
export const Podcast = (p) => <i className={classnames("fa fa-podcast", iconOptions(p), p.className)}/>
export const Quora = (p) => <i className={classnames("fa fa-quora", iconOptions(p), p.className)}/>
export const Ravelry = (p) => <i className={classnames("fa fa-ravelry", iconOptions(p), p.className)}/>
export const S15 = (p) => <i className={classnames("fa fa-s15", iconOptions(p), p.className)}/>
export const Shower = (p) => <i className={classnames("fa fa-shower", iconOptions(p), p.className)}/>
export const SnowflakeO = (p) => <i className={classnames("fa fa-snowflake-o", iconOptions(p), p.className)}/>
export const Superpowers = (p) => <i className={classnames("fa fa-superpowers", iconOptions(p), p.className)}/>
export const Telegram = (p) => <i className={classnames("fa fa-telegram", iconOptions(p), p.className)}/>
export const Thermometer = (p) => <i className={classnames("fa fa-thermometer", iconOptions(p), p.className)}/>
export const Thermometer0 = (p) => <i className={classnames("fa fa-thermometer-0", iconOptions(p), p.className)}/>
export const Thermometer1 = (p) => <i className={classnames("fa fa-thermometer-1", iconOptions(p), p.className)}/>
export const Thermometer2 = (p) => <i className={classnames("fa fa-thermometer-2", iconOptions(p), p.className)}/>
export const Thermometer3 = (p) => <i className={classnames("fa fa-thermometer-3", iconOptions(p), p.className)}/>
export const Thermometer4 = (p) => <i className={classnames("fa fa-thermometer-4", iconOptions(p), p.className)}/>
export const ThermometerEmpty = (p) => <i className={classnames("fa fa-thermometer-empty", iconOptions(p), p.className)}/>
export const ThermometerFull = (p) => <i className={classnames("fa fa-thermometer-full", iconOptions(p), p.className)}/>
export const ThermometerHalf = (p) => <i className={classnames("fa fa-thermometer-half", iconOptions(p), p.className)}/>
export const ThermometerQuarter = (p) => <i className={classnames("fa fa-thermometer-quarter", iconOptions(p), p.className)}/>
export const ThermometerThreeQuarters = (p) => <i className={classnames("fa fa-thermometer-three-quarters", iconOptions(p), p.className)}/>
export const TimesRectangle = (p) => <i className={classnames("fa fa-times-rectangle", iconOptions(p), p.className)}/>
export const TimesRectangleO = (p) => <i className={classnames("fa fa-times-rectangle-o", iconOptions(p), p.className)}/>
export const UserCircle = (p) => <i className={classnames("fa fa-user-circle", iconOptions(p), p.className)}/>
export const UserCircleO = (p) => <i className={classnames("fa fa-user-circle-o", iconOptions(p), p.className)}/>
export const UserO = (p) => <i className={classnames("fa fa-user-o", iconOptions(p), p.className)}/>
export const Vcard = (p) => <i className={classnames("fa fa-vcard", iconOptions(p), p.className)}/>
export const VcardO = (p) => <i className={classnames("fa fa-vcard-o", iconOptions(p), p.className)}/>
export const WindowClose = (p) => <i className={classnames("fa fa-window-close", iconOptions(p), p.className)}/>
export const WindowCloseO = (p) => <i className={classnames("fa fa-window-close-o", iconOptions(p), p.className)}/>
export const WindowMaximize = (p) => <i className={classnames("fa fa-window-maximize", iconOptions(p), p.className)}/>
export const WindowMinimize = (p) => <i className={classnames("fa fa-window-minimize", iconOptions(p), p.className)}/>
export const WindowRestore = (p) => <i className={classnames("fa fa-window-restore", iconOptions(p), p.className)}/>
export const Wpexplorer = (p) => <i className={classnames("fa fa-wpexplorer", iconOptions(p), p.className)}/>
export const Adjust = (p) => <i className={classnames("fa fa-adjust", iconOptions(p), p.className)}/>
export const AmericanSignLanguageInterpreting = (p) => <i className={classnames("fa fa-american-sign-language-interpreting", iconOptions(p), p.className)}/>
export const Anchor = (p) => <i className={classnames("fa fa-anchor", iconOptions(p), p.className)}/>
export const Archive = (p) => <i className={classnames("fa fa-archive", iconOptions(p), p.className)}/>
export const AreaChart = (p) => <i className={classnames("fa fa-area-chart", iconOptions(p), p.className)}/>
export const Arrows = (p) => <i className={classnames("fa fa-arrows", iconOptions(p), p.className)}/>
export const ArrowsH = (p) => <i className={classnames("fa fa-arrows-h", iconOptions(p), p.className)}/>
export const ArrowsV = (p) => <i className={classnames("fa fa-arrows-v", iconOptions(p), p.className)}/>
export const AslInterpreting = (p) => <i className={classnames("fa fa-asl-interpreting", iconOptions(p), p.className)}/>
export const AssistiveListeningSystems = (p) => <i className={classnames("fa fa-assistive-listening-systems", iconOptions(p), p.className)}/>
export const Asterisk = (p) => <i className={classnames("fa fa-asterisk", iconOptions(p), p.className)}/>
export const At = (p) => <i className={classnames("fa fa-at", iconOptions(p), p.className)}/>
export const AudioDescription = (p) => <i className={classnames("fa fa-audio-description", iconOptions(p), p.className)}/>
export const Automobile = (p) => <i className={classnames("fa fa-automobile", iconOptions(p), p.className)}/>
export const BalanceScale = (p) => <i className={classnames("fa fa-balance-scale", iconOptions(p), p.className)}/>
export const Ban = (p) => <i className={classnames("fa fa-ban", iconOptions(p), p.className)}/>
export const Bank = (p) => <i className={classnames("fa fa-bank", iconOptions(p), p.className)}/>
export const BarChart = (p) => <i className={classnames("fa fa-bar-chart", iconOptions(p), p.className)}/>
export const BarChartO = (p) => <i className={classnames("fa fa-bar-chart-o", iconOptions(p), p.className)}/>
export const Barcode = (p) => <i className={classnames("fa fa-barcode", iconOptions(p), p.className)}/>
export const Bars = (p) => <i className={classnames("fa fa-bars", iconOptions(p), p.className)}/>
export const Battery = (p) => <i className={classnames("fa fa-battery", iconOptions(p), p.className)}/>
export const Battery0 = (p) => <i className={classnames("fa fa-battery-0", iconOptions(p), p.className)}/>
export const Battery1 = (p) => <i className={classnames("fa fa-battery-1", iconOptions(p), p.className)}/>
export const Battery2 = (p) => <i className={classnames("fa fa-battery-2", iconOptions(p), p.className)}/>
export const Battery3 = (p) => <i className={classnames("fa fa-battery-3", iconOptions(p), p.className)}/>
export const Battery4 = (p) => <i className={classnames("fa fa-battery-4", iconOptions(p), p.className)}/>
export const BatteryEmpty = (p) => <i className={classnames("fa fa-battery-empty", iconOptions(p), p.className)}/>
export const BatteryFull = (p) => <i className={classnames("fa fa-battery-full", iconOptions(p), p.className)}/>
export const BatteryHalf = (p) => <i className={classnames("fa fa-battery-half", iconOptions(p), p.className)}/>
export const BatteryQuarter = (p) => <i className={classnames("fa fa-battery-quarter", iconOptions(p), p.className)}/>
export const BatteryThreeQuarters = (p) => <i className={classnames("fa fa-battery-three-quarters", iconOptions(p), p.className)}/>
export const Bed = (p) => <i className={classnames("fa fa-bed", iconOptions(p), p.className)}/>
export const Beer = (p) => <i className={classnames("fa fa-beer", iconOptions(p), p.className)}/>
export const Bell = (p) => <i className={classnames("fa fa-bell", iconOptions(p), p.className)}/>
export const BellO = (p) => <i className={classnames("fa fa-bell-o", iconOptions(p), p.className)}/>
export const BellSlash = (p) => <i className={classnames("fa fa-bell-slash", iconOptions(p), p.className)}/>
export const BellSlashO = (p) => <i className={classnames("fa fa-bell-slash-o", iconOptions(p), p.className)}/>
export const Bicycle = (p) => <i className={classnames("fa fa-bicycle", iconOptions(p), p.className)}/>
export const Binoculars = (p) => <i className={classnames("fa fa-binoculars", iconOptions(p), p.className)}/>
export const BirthdayCake = (p) => <i className={classnames("fa fa-birthday-cake", iconOptions(p), p.className)}/>
export const Blind = (p) => <i className={classnames("fa fa-blind", iconOptions(p), p.className)}/>
export const Bluetooth = (p) => <i className={classnames("fa fa-bluetooth", iconOptions(p), p.className)}/>
export const BluetoothB = (p) => <i className={classnames("fa fa-bluetooth-b", iconOptions(p), p.className)}/>
export const Bolt = (p) => <i className={classnames("fa fa-bolt", iconOptions(p), p.className)}/>
export const Bomb = (p) => <i className={classnames("fa fa-bomb", iconOptions(p), p.className)}/>
export const Book = (p) => <i className={classnames("fa fa-book", iconOptions(p), p.className)}/>
export const Bookmark = (p) => <i className={classnames("fa fa-bookmark", iconOptions(p), p.className)}/>
export const BookmarkO = (p) => <i className={classnames("fa fa-bookmark-o", iconOptions(p), p.className)}/>
export const Braille = (p) => <i className={classnames("fa fa-braille", iconOptions(p), p.className)}/>
export const Briefcase = (p) => <i className={classnames("fa fa-briefcase", iconOptions(p), p.className)}/>
export const Bug = (p) => <i className={classnames("fa fa-bug", iconOptions(p), p.className)}/>
export const Building = (p) => <i className={classnames("fa fa-building", iconOptions(p), p.className)}/>
export const BuildingO = (p) => <i className={classnames("fa fa-building-o", iconOptions(p), p.className)}/>
export const Bullhorn = (p) => <i className={classnames("fa fa-bullhorn", iconOptions(p), p.className)}/>
export const Bullseye = (p) => <i className={classnames("fa fa-bullseye", iconOptions(p), p.className)}/>
export const Bus = (p) => <i className={classnames("fa fa-bus", iconOptions(p), p.className)}/>
export const Cab = (p) => <i className={classnames("fa fa-cab", iconOptions(p), p.className)}/>
export const Calculator = (p) => <i className={classnames("fa fa-calculator", iconOptions(p), p.className)}/>
export const Calendar = (p) => <i className={classnames("fa fa-calendar", iconOptions(p), p.className)}/>
export const CalendarCheckO = (p) => <i className={classnames("fa fa-calendar-check-o", iconOptions(p), p.className)}/>
export const CalendarMinusO = (p) => <i className={classnames("fa fa-calendar-minus-o", iconOptions(p), p.className)}/>
export const CalendarO = (p) => <i className={classnames("fa fa-calendar-o", iconOptions(p), p.className)}/>
export const CalendarPlusO = (p) => <i className={classnames("fa fa-calendar-plus-o", iconOptions(p), p.className)}/>
export const CalendarTimesO = (p) => <i className={classnames("fa fa-calendar-times-o", iconOptions(p), p.className)}/>
export const Camera = (p) => <i className={classnames("fa fa-camera", iconOptions(p), p.className)}/>
export const CameraRetro = (p) => <i className={classnames("fa fa-camera-retro", iconOptions(p), p.className)}/>
export const Car = (p) => <i className={classnames("fa fa-car", iconOptions(p), p.className)}/>
export const CaretSquareODown = (p) => <i className={classnames("fa fa-caret-square-o-down", iconOptions(p), p.className)}/>
export const CaretSquareOLeft = (p) => <i className={classnames("fa fa-caret-square-o-left", iconOptions(p), p.className)}/>
export const CaretSquareORight = (p) => <i className={classnames("fa fa-caret-square-o-right", iconOptions(p), p.className)}/>
export const CaretSquareOUp = (p) => <i className={classnames("fa fa-caret-square-o-up", iconOptions(p), p.className)}/>
export const CartArrowDown = (p) => <i className={classnames("fa fa-cart-arrow-down", iconOptions(p), p.className)}/>
export const CartPlus = (p) => <i className={classnames("fa fa-cart-plus", iconOptions(p), p.className)}/>
export const Cc = (p) => <i className={classnames("fa fa-cc", iconOptions(p), p.className)}/>
export const Certificate = (p) => <i className={classnames("fa fa-certificate", iconOptions(p), p.className)}/>
export const Check = (p) => <i className={classnames("fa fa-check", iconOptions(p), p.className)}/>
export const CheckCircle = (p) => <i className={classnames("fa fa-check-circle", iconOptions(p), p.className)}/>
export const CheckCircleO = (p) => <i className={classnames("fa fa-check-circle-o", iconOptions(p), p.className)}/>
export const CheckSquare = (p) => <i className={classnames("fa fa-check-square", iconOptions(p), p.className)}/>
export const CheckSquareO = (p) => <i className={classnames("fa fa-check-square-o", iconOptions(p), p.className)}/>
export const Child = (p) => <i className={classnames("fa fa-child", iconOptions(p), p.className)}/>
export const Circle = (p) => <i className={classnames("fa fa-circle", iconOptions(p), p.className)}/>
export const CircleO = (p) => <i className={classnames("fa fa-circle-o", iconOptions(p), p.className)}/>
export const CircleONotch = (p) => <i className={classnames("fa fa-circle-o-notch", iconOptions(p), p.className)}/>
export const CircleThin = (p) => <i className={classnames("fa fa-circle-thin", iconOptions(p), p.className)}/>
export const ClockO = (p) => <i className={classnames("fa fa-clock-o", iconOptions(p), p.className)}/>
export const Clone = (p) => <i className={classnames("fa fa-clone", iconOptions(p), p.className)}/>
export const Close = (p) => <i className={classnames("fa fa-close", iconOptions(p), p.className)}/>
export const Cloud = (p) => <i className={classnames("fa fa-cloud", iconOptions(p), p.className)}/>
export const CloudDownload = (p) => <i className={classnames("fa fa-cloud-download", iconOptions(p), p.className)}/>
export const CloudUpload = (p) => <i className={classnames("fa fa-cloud-upload", iconOptions(p), p.className)}/>
export const Code = (p) => <i className={classnames("fa fa-code", iconOptions(p), p.className)}/>
export const CodeFork = (p) => <i className={classnames("fa fa-code-fork", iconOptions(p), p.className)}/>
export const Coffee = (p) => <i className={classnames("fa fa-coffee", iconOptions(p), p.className)}/>
export const Cog = (p) => <i className={classnames("fa fa-cog", iconOptions(p), p.className)}/>
export const Cogs = (p) => <i className={classnames("fa fa-cogs", iconOptions(p), p.className)}/>
export const Comment = (p) => <i className={classnames("fa fa-comment", iconOptions(p), p.className)}/>
export const CommentO = (p) => <i className={classnames("fa fa-comment-o", iconOptions(p), p.className)}/>
export const Commenting = (p) => <i className={classnames("fa fa-commenting", iconOptions(p), p.className)}/>
export const CommentingO = (p) => <i className={classnames("fa fa-commenting-o", iconOptions(p), p.className)}/>
export const Comments = (p) => <i className={classnames("fa fa-comments", iconOptions(p), p.className)}/>
export const CommentsO = (p) => <i className={classnames("fa fa-comments-o", iconOptions(p), p.className)}/>
export const Compass = (p) => <i className={classnames("fa fa-compass", iconOptions(p), p.className)}/>
export const Copyright = (p) => <i className={classnames("fa fa-copyright", iconOptions(p), p.className)}/>
export const CreativeCommons = (p) => <i className={classnames("fa fa-creative-commons", iconOptions(p), p.className)}/>
export const CreditCard = (p) => <i className={classnames("fa fa-credit-card", iconOptions(p), p.className)}/>
export const CreditCardAlt = (p) => <i className={classnames("fa fa-credit-card-alt", iconOptions(p), p.className)}/>
export const Crop = (p) => <i className={classnames("fa fa-crop", iconOptions(p), p.className)}/>
export const Crosshairs = (p) => <i className={classnames("fa fa-crosshairs", iconOptions(p), p.className)}/>
export const Cube = (p) => <i className={classnames("fa fa-cube", iconOptions(p), p.className)}/>
export const Cubes = (p) => <i className={classnames("fa fa-cubes", iconOptions(p), p.className)}/>
export const Cutlery = (p) => <i className={classnames("fa fa-cutlery", iconOptions(p), p.className)}/>
export const Dashboard = (p) => <i className={classnames("fa fa-dashboard", iconOptions(p), p.className)}/>
export const Database = (p) => <i className={classnames("fa fa-database", iconOptions(p), p.className)}/>
export const Deaf = (p) => <i className={classnames("fa fa-deaf", iconOptions(p), p.className)}/>
export const Deafness = (p) => <i className={classnames("fa fa-deafness", iconOptions(p), p.className)}/>
export const Desktop = (p) => <i className={classnames("fa fa-desktop", iconOptions(p), p.className)}/>
export const Diamond = (p) => <i className={classnames("fa fa-diamond", iconOptions(p), p.className)}/>
export const DotCircleO = (p) => <i className={classnames("fa fa-dot-circle-o", iconOptions(p), p.className)}/>
export const Download = (p) => <i className={classnames("fa fa-download", iconOptions(p), p.className)}/>
export const Edit = (p) => <i className={classnames("fa fa-edit", iconOptions(p), p.className)}/>
export const EllipsisH = (p) => <i className={classnames("fa fa-ellipsis-h", iconOptions(p), p.className)}/>
export const EllipsisV = (p) => <i className={classnames("fa fa-ellipsis-v", iconOptions(p), p.className)}/>
export const Envelope = (p) => <i className={classnames("fa fa-envelope", iconOptions(p), p.className)}/>
export const EnvelopeO = (p) => <i className={classnames("fa fa-envelope-o", iconOptions(p), p.className)}/>
export const EnvelopeSquare = (p) => <i className={classnames("fa fa-envelope-square", iconOptions(p), p.className)}/>
export const Eraser = (p) => <i className={classnames("fa fa-eraser", iconOptions(p), p.className)}/>
export const Exchange = (p) => <i className={classnames("fa fa-exchange", iconOptions(p), p.className)}/>
export const Exclamation = (p) => <i className={classnames("fa fa-exclamation", iconOptions(p), p.className)}/>
export const ExclamationCircle = (p) => <i className={classnames("fa fa-exclamation-circle", iconOptions(p), p.className)}/>
export const ExclamationTriangle = (p) => <i className={classnames("fa fa-exclamation-triangle", iconOptions(p), p.className)}/>
export const ExternalLink = (p) => <i className={classnames("fa fa-external-link", iconOptions(p), p.className)}/>
export const ExternalLinkSquare = (p) => <i className={classnames("fa fa-external-link-square", iconOptions(p), p.className)}/>
export const Eye = (p) => <i className={classnames("fa fa-eye", iconOptions(p), p.className)}/>
export const EyeSlash = (p) => <i className={classnames("fa fa-eye-slash", iconOptions(p), p.className)}/>
export const Eyedropper = (p) => <i className={classnames("fa fa-eyedropper", iconOptions(p), p.className)}/>
export const Fax = (p) => <i className={classnames("fa fa-fax", iconOptions(p), p.className)}/>
export const Feed = (p) => <i className={classnames("fa fa-feed", iconOptions(p), p.className)}/>
export const Female = (p) => <i className={classnames("fa fa-female", iconOptions(p), p.className)}/>
export const FighterJet = (p) => <i className={classnames("fa fa-fighter-jet", iconOptions(p), p.className)}/>
export const FileArchiveO = (p) => <i className={classnames("fa fa-file-archive-o", iconOptions(p), p.className)}/>
export const FileAudioO = (p) => <i className={classnames("fa fa-file-audio-o", iconOptions(p), p.className)}/>
export const FileCodeO = (p) => <i className={classnames("fa fa-file-code-o", iconOptions(p), p.className)}/>
export const FileExcelO = (p) => <i className={classnames("fa fa-file-excel-o", iconOptions(p), p.className)}/>
export const FileImageO = (p) => <i className={classnames("fa fa-file-image-o", iconOptions(p), p.className)}/>
export const FileMovieO = (p) => <i className={classnames("fa fa-file-movie-o", iconOptions(p), p.className)}/>
export const FilePdfO = (p) => <i className={classnames("fa fa-file-pdf-o", iconOptions(p), p.className)}/>
export const FilePhotoO = (p) => <i className={classnames("fa fa-file-photo-o", iconOptions(p), p.className)}/>
export const FilePictureO = (p) => <i className={classnames("fa fa-file-picture-o", iconOptions(p), p.className)}/>
export const FilePowerpointO = (p) => <i className={classnames("fa fa-file-powerpoint-o", iconOptions(p), p.className)}/>
export const FileSoundO = (p) => <i className={classnames("fa fa-file-sound-o", iconOptions(p), p.className)}/>
export const FileVideoO = (p) => <i className={classnames("fa fa-file-video-o", iconOptions(p), p.className)}/>
export const FileWordO = (p) => <i className={classnames("fa fa-file-word-o", iconOptions(p), p.className)}/>
export const FileZipO = (p) => <i className={classnames("fa fa-file-zip-o", iconOptions(p), p.className)}/>
export const Film = (p) => <i className={classnames("fa fa-film", iconOptions(p), p.className)}/>
export const Filter = (p) => <i className={classnames("fa fa-filter", iconOptions(p), p.className)}/>
export const Fire = (p) => <i className={classnames("fa fa-fire", iconOptions(p), p.className)}/>
export const FireExtinguisher = (p) => <i className={classnames("fa fa-fire-extinguisher", iconOptions(p), p.className)}/>
export const FlagCheckered = (p) => <i className={classnames("fa fa-flag-checkered", iconOptions(p), p.className)}/>
export const FlagO = (p) => <i className={classnames("fa fa-flag-o", iconOptions(p), p.className)}/>
export const Flash = (p) => <i className={classnames("fa fa-flash", iconOptions(p), p.className)}/>
export const Flask = (p) => <i className={classnames("fa fa-flask", iconOptions(p), p.className)}/>
export const Folder = (p) => <i className={classnames("fa fa-folder", iconOptions(p), p.className)}/>
export const FolderO = (p) => <i className={classnames("fa fa-folder-o", iconOptions(p), p.className)}/>
export const FolderOpen = (p) => <i className={classnames("fa fa-folder-open", iconOptions(p), p.className)}/>
export const FolderOpenO = (p) => <i className={classnames("fa fa-folder-open-o", iconOptions(p), p.className)}/>
export const FrownO = (p) => <i className={classnames("fa fa-frown-o", iconOptions(p), p.className)}/>
export const Futbol = (p) => <i className={classnames("fa fa-futbol", iconOptions(p), p.className)}/>
export const Gamepad = (p) => <i className={classnames("fa fa-gamepad", iconOptions(p), p.className)}/>
export const Gavel = (p) => <i className={classnames("fa fa-gavel", iconOptions(p), p.className)}/>
export const Gear = (p) => <i className={classnames("fa fa-gear", iconOptions(p), p.className)}/>
export const Gears = (p) => <i className={classnames("fa fa-gears", iconOptions(p), p.className)}/>
export const Gift = (p) => <i className={classnames("fa fa-gift", iconOptions(p), p.className)}/>
export const Glass = (p) => <i className={classnames("fa fa-glass", iconOptions(p), p.className)}/>
export const Globe = (p) => <i className={classnames("fa fa-globe", iconOptions(p), p.className)}/>
export const GraduationCap = (p) => <i className={classnames("fa fa-graduation-cap", iconOptions(p), p.className)}/>
export const Group = (p) => <i className={classnames("fa fa-group", iconOptions(p), p.className)}/>
export const HandGrabO = (p) => <i className={classnames("fa fa-hand-grab-o", iconOptions(p), p.className)}/>
export const HandLizardO = (p) => <i className={classnames("fa fa-hand-lizard-o", iconOptions(p), p.className)}/>
export const HandPaperO = (p) => <i className={classnames("fa fa-hand-paper-o", iconOptions(p), p.className)}/>
export const HandPeaceO = (p) => <i className={classnames("fa fa-hand-peace-o", iconOptions(p), p.className)}/>
export const HandPointerO = (p) => <i className={classnames("fa fa-hand-pointer-o", iconOptions(p), p.className)}/>
export const HandRockO = (p) => <i className={classnames("fa fa-hand-rock-o", iconOptions(p), p.className)}/>
export const HandScissorsO = (p) => <i className={classnames("fa fa-hand-scissors-o", iconOptions(p), p.className)}/>
export const HandSpockO = (p) => <i className={classnames("fa fa-hand-spock-o", iconOptions(p), p.className)}/>
export const HandStopO = (p) => <i className={classnames("fa fa-hand-stop-o", iconOptions(p), p.className)}/>
export const HardOfHearing = (p) => <i className={classnames("fa fa-hard-of-hearing", iconOptions(p), p.className)}/>
export const Hashtag = (p) => <i className={classnames("fa fa-hashtag", iconOptions(p), p.className)}/>
export const HddO = (p) => <i className={classnames("fa fa-hdd-o", iconOptions(p), p.className)}/>
export const Headphones = (p) => <i className={classnames("fa fa-headphones", iconOptions(p), p.className)}/>
export const Heart = (p) => <i className={classnames("fa fa-heart", iconOptions(p), p.className)}/>
export const HeartO = (p) => <i className={classnames("fa fa-heart-o", iconOptions(p), p.className)}/>
export const Heartbeat = (p) => <i className={classnames("fa fa-heartbeat", iconOptions(p), p.className)}/>
export const History = (p) => <i className={classnames("fa fa-history", iconOptions(p), p.className)}/>
export const Home = (p) => <i className={classnames("fa fa-home", iconOptions(p), p.className)}/>
export const Hotel = (p) => <i className={classnames("fa fa-hotel", iconOptions(p), p.className)}/>
export const Hourglass = (p) => <i className={classnames("fa fa-hourglass", iconOptions(p), p.className)}/>
export const Hourglass1 = (p) => <i className={classnames("fa fa-hourglass-1", iconOptions(p), p.className)}/>
export const Hourglass2 = (p) => <i className={classnames("fa fa-hourglass-2", iconOptions(p), p.className)}/>
export const Hourglass3 = (p) => <i className={classnames("fa fa-hourglass-3", iconOptions(p), p.className)}/>
export const HourglassEnd = (p) => <i className={classnames("fa fa-hourglass-end", iconOptions(p), p.className)}/>
export const HourglassHalf = (p) => <i className={classnames("fa fa-hourglass-half", iconOptions(p), p.className)}/>
export const HourglassO = (p) => <i className={classnames("fa fa-hourglass-o", iconOptions(p), p.className)}/>
export const HourglassStart = (p) => <i className={classnames("fa fa-hourglass-start", iconOptions(p), p.className)}/>
export const ICursor = (p) => <i className={classnames("fa fa-i-cursor", iconOptions(p), p.className)}/>
export const Image = (p) => <i className={classnames("fa fa-image", iconOptions(p), p.className)}/>
export const Inbox = (p) => <i className={classnames("fa fa-inbox", iconOptions(p), p.className)}/>
export const Industry = (p) => <i className={classnames("fa fa-industry", iconOptions(p), p.className)}/>
export const Info = (p) => <i className={classnames("fa fa-info", iconOptions(p), p.className)}/>
export const InfoCircle = (p) => <i className={classnames("fa fa-info-circle", iconOptions(p), p.className)}/>
export const Institution = (p) => <i className={classnames("fa fa-institution", iconOptions(p), p.className)}/>
export const Key = (p) => <i className={classnames("fa fa-key", iconOptions(p), p.className)}/>
export const KeyboardO = (p) => <i className={classnames("fa fa-keyboard-o", iconOptions(p), p.className)}/>
export const Language = (p) => <i className={classnames("fa fa-language", iconOptions(p), p.className)}/>
export const Laptop = (p) => <i className={classnames("fa fa-laptop", iconOptions(p), p.className)}/>
export const Leaf = (p) => <i className={classnames("fa fa-leaf", iconOptions(p), p.className)}/>
export const Legal = (p) => <i className={classnames("fa fa-legal", iconOptions(p), p.className)}/>
export const LemonO = (p) => <i className={classnames("fa fa-lemon-o", iconOptions(p), p.className)}/>
export const LevelDown = (p) => <i className={classnames("fa fa-level-down", iconOptions(p), p.className)}/>
export const LevelUp = (p) => <i className={classnames("fa fa-level-up", iconOptions(p), p.className)}/>
export const LifeBouy = (p) => <i className={classnames("fa fa-life-bouy", iconOptions(p), p.className)}/>
export const LifeBuoy = (p) => <i className={classnames("fa fa-life-buoy", iconOptions(p), p.className)}/>
export const LifeRing = (p) => <i className={classnames("fa fa-life-ring", iconOptions(p), p.className)}/>
export const LifeSaver = (p) => <i className={classnames("fa fa-life-saver", iconOptions(p), p.className)}/>
export const LightbulbO = (p) => <i className={classnames("fa fa-lightbulb-o", iconOptions(p), p.className)}/>
export const LineChart = (p) => <i className={classnames("fa fa-line-chart", iconOptions(p), p.className)}/>
export const LocationArrow = (p) => <i className={classnames("fa fa-location-arrow", iconOptions(p), p.className)}/>
export const Lock = (p) => <i className={classnames("fa fa-lock", iconOptions(p), p.className)}/>
export const LowVision = (p) => <i className={classnames("fa fa-low-vision", iconOptions(p), p.className)}/>
export const Magic = (p) => <i className={classnames("fa fa-magic", iconOptions(p), p.className)}/>
export const Magnet = (p) => <i className={classnames("fa fa-magnet", iconOptions(p), p.className)}/>
export const MailForward = (p) => <i className={classnames("fa fa-mail-forward", iconOptions(p), p.className)}/>
export const MailReply = (p) => <i className={classnames("fa fa-mail-reply", iconOptions(p), p.className)}/>
export const MailReplyAll = (p) => <i className={classnames("fa fa-mail-reply-all", iconOptions(p), p.className)}/>
export const Male = (p) => <i className={classnames("fa fa-male", iconOptions(p), p.className)}/>
export const Map = (p) => <i className={classnames("fa fa-map", iconOptions(p), p.className)}/>
export const MapMarker = (p) => <i className={classnames("fa fa-map-marker", iconOptions(p), p.className)}/>
export const MapO = (p) => <i className={classnames("fa fa-map-o", iconOptions(p), p.className)}/>
export const MapPin = (p) => <i className={classnames("fa fa-map-pin", iconOptions(p), p.className)}/>
export const MapSigns = (p) => <i className={classnames("fa fa-map-signs", iconOptions(p), p.className)}/>
export const MehO = (p) => <i className={classnames("fa fa-meh-o", iconOptions(p), p.className)}/>
export const Microphone = (p) => <i className={classnames("fa fa-microphone", iconOptions(p), p.className)}/>
export const MicrophoneSlash = (p) => <i className={classnames("fa fa-microphone-slash", iconOptions(p), p.className)}/>
export const Minus = (p) => <i className={classnames("fa fa-minus", iconOptions(p), p.className)}/>
export const MinusCircle = (p) => <i className={classnames("fa fa-minus-circle", iconOptions(p), p.className)}/>
export const MinusSquare = (p) => <i className={classnames("fa fa-minus-square", iconOptions(p), p.className)}/>
export const MinusSquareO = (p) => <i className={classnames("fa fa-minus-square-o", iconOptions(p), p.className)}/>
export const Mobile = (p) => <i className={classnames("fa fa-mobile", iconOptions(p), p.className)}/>
export const MobilePhone = (p) => <i className={classnames("fa fa-mobile-phone", iconOptions(p), p.className)}/>
export const Money = (p) => <i className={classnames("fa fa-money", iconOptions(p), p.className)}/>
export const MoonO = (p) => <i className={classnames("fa fa-moon-o", iconOptions(p), p.className)}/>
export const MortarBoard = (p) => <i className={classnames("fa fa-mortar-board", iconOptions(p), p.className)}/>
export const Motorcycle = (p) => <i className={classnames("fa fa-motorcycle", iconOptions(p), p.className)}/>
export const MousePointer = (p) => <i className={classnames("fa fa-mouse-pointer", iconOptions(p), p.className)}/>
export const Music = (p) => <i className={classnames("fa fa-music", iconOptions(p), p.className)}/>
export const Navicon = (p) => <i className={classnames("fa fa-navicon", iconOptions(p), p.className)}/>
export const NewspaperO = (p) => <i className={classnames("fa fa-newspaper-o", iconOptions(p), p.className)}/>
export const ObjectGroup = (p) => <i className={classnames("fa fa-object-group", iconOptions(p), p.className)}/>
export const ObjectUngroup = (p) => <i className={classnames("fa fa-object-ungroup", iconOptions(p), p.className)}/>
export const PaintBrush = (p) => <i className={classnames("fa fa-paint-brush", iconOptions(p), p.className)}/>
export const PaperPlane = (p) => <i className={classnames("fa fa-paper-plane", iconOptions(p), p.className)}/>
export const PaperPlaneO = (p) => <i className={classnames("fa fa-paper-plane-o", iconOptions(p), p.className)}/>
export const Paw = (p) => <i className={classnames("fa fa-paw", iconOptions(p), p.className)}/>
export const Pencil = (p) => <i className={classnames("fa fa-pencil", iconOptions(p), p.className)}/>
export const PencilSquare = (p) => <i className={classnames("fa fa-pencil-square", iconOptions(p), p.className)}/>
export const PencilSquareO = (p) => <i className={classnames("fa fa-pencil-square-o", iconOptions(p), p.className)}/>
export const Percent = (p) => <i className={classnames("fa fa-percent", iconOptions(p), p.className)}/>
export const Phone = (p) => <i className={classnames("fa fa-phone", iconOptions(p), p.className)}/>
export const PhoneSquare = (p) => <i className={classnames("fa fa-phone-square", iconOptions(p), p.className)}/>
export const Photo = (p) => <i className={classnames("fa fa-photo", iconOptions(p), p.className)}/>
export const PictureO = (p) => <i className={classnames("fa fa-picture-o", iconOptions(p), p.className)}/>
export const PieChart = (p) => <i className={classnames("fa fa-pie-chart", iconOptions(p), p.className)}/>
export const Plane = (p) => <i className={classnames("fa fa-plane", iconOptions(p), p.className)}/>
export const Plug = (p) => <i className={classnames("fa fa-plug", iconOptions(p), p.className)}/>
export const Plus = (p) => <i className={classnames("fa fa-plus", iconOptions(p), p.className)}/>
export const PlusCircle = (p) => <i className={classnames("fa fa-plus-circle", iconOptions(p), p.className)}/>
export const PlusSquare = (p) => <i className={classnames("fa fa-plus-square", iconOptions(p), p.className)}/>
export const PlusSquareO = (p) => <i className={classnames("fa fa-plus-square-o", iconOptions(p), p.className)}/>
export const PowerOff = (p) => <i className={classnames("fa fa-power-off", iconOptions(p), p.className)}/>
export const Print = (p) => <i className={classnames("fa fa-print", iconOptions(p), p.className)}/>
export const PuzzlePiece = (p) => <i className={classnames("fa fa-puzzle-piece", iconOptions(p), p.className)}/>
export const Qrcode = (p) => <i className={classnames("fa fa-qrcode", iconOptions(p), p.className)}/>
export const Question = (p) => <i className={classnames("fa fa-question", iconOptions(p), p.className)}/>
export const QuestionCircle = (p) => <i className={classnames("fa fa-question-circle", iconOptions(p), p.className)}/>
export const QuestionCircleO = (p) => <i className={classnames("fa fa-question-circle-o", iconOptions(p), p.className)}/>
export const QuoteLeft = (p) => <i className={classnames("fa fa-quote-left", iconOptions(p), p.className)}/>
export const QuoteRight = (p) => <i className={classnames("fa fa-quote-right", iconOptions(p), p.className)}/>
export const Random = (p) => <i className={classnames("fa fa-random", iconOptions(p), p.className)}/>
export const Recycle = (p) => <i className={classnames("fa fa-recycle", iconOptions(p), p.className)}/>
export const Refresh = (p) => <i className={classnames("fa fa-refresh", iconOptions(p), p.className)}/>
export const Registered = (p) => <i className={classnames("fa fa-registered", iconOptions(p), p.className)}/>
export const Remove = (p) => <i className={classnames("fa fa-remove", iconOptions(p), p.className)}/>
export const Reorder = (p) => <i className={classnames("fa fa-reorder", iconOptions(p), p.className)}/>
export const Reply = (p) => <i className={classnames("fa fa-reply", iconOptions(p), p.className)}/>
export const ReplyAll = (p) => <i className={classnames("fa fa-reply-all", iconOptions(p), p.className)}/>
export const Retweet = (p) => <i className={classnames("fa fa-retweet", iconOptions(p), p.className)}/>
export const Road = (p) => <i className={classnames("fa fa-road", iconOptions(p), p.className)}/>
export const Rocket = (p) => <i className={classnames("fa fa-rocket", iconOptions(p), p.className)}/>
export const Rss = (p) => <i className={classnames("fa fa-rss", iconOptions(p), p.className)}/>
export const RssSquare = (p) => <i className={classnames("fa fa-rss-square", iconOptions(p), p.className)}/>
export const SearchMinus = (p) => <i className={classnames("fa fa-search-minus", iconOptions(p), p.className)}/>
export const SearchPlus = (p) => <i className={classnames("fa fa-search-plus", iconOptions(p), p.className)}/>
export const Send = (p) => <i className={classnames("fa fa-send", iconOptions(p), p.className)}/>
export const SendO = (p) => <i className={classnames("fa fa-send-o", iconOptions(p), p.className)}/>
export const Server = (p) => <i className={classnames("fa fa-server", iconOptions(p), p.className)}/>
export const Share = (p) => <i className={classnames("fa fa-share", iconOptions(p), p.className)}/>
export const ShareAlt = (p) => <i className={classnames("fa fa-share-alt", iconOptions(p), p.className)}/>
export const ShareAltSquare = (p) => <i className={classnames("fa fa-share-alt-square", iconOptions(p), p.className)}/>
export const ShareSquare = (p) => <i className={classnames("fa fa-share-square", iconOptions(p), p.className)}/>
export const ShareSquareO = (p) => <i className={classnames("fa fa-share-square-o", iconOptions(p), p.className)}/>
export const Shield = (p) => <i className={classnames("fa fa-shield", iconOptions(p), p.className)}/>
export const Ship = (p) => <i className={classnames("fa fa-ship", iconOptions(p), p.className)}/>
export const ShoppingBag = (p) => <i className={classnames("fa fa-shopping-bag", iconOptions(p), p.className)}/>
export const ShoppingBasket = (p) => <i className={classnames("fa fa-shopping-basket", iconOptions(p), p.className)}/>
export const ShoppingCart = (p) => <i className={classnames("fa fa-shopping-cart", iconOptions(p), p.className)}/>
export const SignIn = (p) => <i className={classnames("fa fa-sign-in", iconOptions(p), p.className)}/>
export const SignLanguage = (p) => <i className={classnames("fa fa-sign-language", iconOptions(p), p.className)}/>
export const SignOut = (p) => <i className={classnames("fa fa-sign-out", iconOptions(p), p.className)}/>
export const Signal = (p) => <i className={classnames("fa fa-signal", iconOptions(p), p.className)}/>
export const Signing = (p) => <i className={classnames("fa fa-signing", iconOptions(p), p.className)}/>
export const Sitemap = (p) => <i className={classnames("fa fa-sitemap", iconOptions(p), p.className)}/>
export const Sliders = (p) => <i className={classnames("fa fa-sliders", iconOptions(p), p.className)}/>
export const SmileO = (p) => <i className={classnames("fa fa-smile-o", iconOptions(p), p.className)}/>
export const SoccerBallO = (p) => <i className={classnames("fa fa-soccer-ball-o", iconOptions(p), p.className)}/>
export const Sort = (p) => <i className={classnames("fa fa-sort", iconOptions(p), p.className)}/>
export const SortAlphaAsc = (p) => <i className={classnames("fa fa-sort-alpha-asc", iconOptions(p), p.className)}/>
export const SortAlphaDesc = (p) => <i className={classnames("fa fa-sort-alpha-desc", iconOptions(p), p.className)}/>
export const SortAmountAsc = (p) => <i className={classnames("fa fa-sort-amount-asc", iconOptions(p), p.className)}/>
export const SortAmountDesc = (p) => <i className={classnames("fa fa-sort-amount-desc", iconOptions(p), p.className)}/>
export const SortAsc = (p) => <i className={classnames("fa fa-sort-asc", iconOptions(p), p.className)}/>
export const SortDesc = (p) => <i className={classnames("fa fa-sort-desc", iconOptions(p), p.className)}/>
export const SortDown = (p) => <i className={classnames("fa fa-sort-down", iconOptions(p), p.className)}/>
export const SortNumericAsc = (p) => <i className={classnames("fa fa-sort-numeric-asc", iconOptions(p), p.className)}/>
export const SortNumericDesc = (p) => <i className={classnames("fa fa-sort-numeric-desc", iconOptions(p), p.className)}/>
export const SortUp = (p) => <i className={classnames("fa fa-sort-up", iconOptions(p), p.className)}/>
export const SpaceShuttle = (p) => <i className={classnames("fa fa-space-shuttle", iconOptions(p), p.className)}/>
export const Spinner = (p) => <i className={classnames("fa fa-spinner", iconOptions(p), p.className)}/>
export const Spoon = (p) => <i className={classnames("fa fa-spoon", iconOptions(p), p.className)}/>
export const Square = (p) => <i className={classnames("fa fa-square", iconOptions(p), p.className)}/>
export const SquareO = (p) => <i className={classnames("fa fa-square-o", iconOptions(p), p.className)}/>
export const Star = (p) => <i className={classnames("fa fa-star", iconOptions(p), p.className)}/>
export const StarHalf = (p) => <i className={classnames("fa fa-star-half", iconOptions(p), p.className)}/>
export const StarHalfEmpty = (p) => <i className={classnames("fa fa-star-half-empty", iconOptions(p), p.className)}/>
export const StarHalfFull = (p) => <i className={classnames("fa fa-star-half-full", iconOptions(p), p.className)}/>
export const StarHalfO = (p) => <i className={classnames("fa fa-star-half-o", iconOptions(p), p.className)}/>
export const StarO = (p) => <i className={classnames("fa fa-star-o", iconOptions(p), p.className)}/>
export const StickyNote = (p) => <i className={classnames("fa fa-sticky-note", iconOptions(p), p.className)}/>
export const StickyNoteO = (p) => <i className={classnames("fa fa-sticky-note-o", iconOptions(p), p.className)}/>
export const StreetView = (p) => <i className={classnames("fa fa-street-view", iconOptions(p), p.className)}/>
export const Suitcase = (p) => <i className={classnames("fa fa-suitcase", iconOptions(p), p.className)}/>
export const SunO = (p) => <i className={classnames("fa fa-sun-o", iconOptions(p), p.className)}/>
export const Support = (p) => <i className={classnames("fa fa-support", iconOptions(p), p.className)}/>
export const Tablet = (p) => <i className={classnames("fa fa-tablet", iconOptions(p), p.className)}/>
export const Tachometer = (p) => <i className={classnames("fa fa-tachometer", iconOptions(p), p.className)}/>
export const Tag = (p) => <i className={classnames("fa fa-tag", iconOptions(p), p.className)}/>
export const Tags = (p) => <i className={classnames("fa fa-tags", iconOptions(p), p.className)}/>
export const Tasks = (p) => <i className={classnames("fa fa-tasks", iconOptions(p), p.className)}/>
export const Taxi = (p) => <i className={classnames("fa fa-taxi", iconOptions(p), p.className)}/>
export const Television = (p) => <i className={classnames("fa fa-television", iconOptions(p), p.className)}/>
export const Terminal = (p) => <i className={classnames("fa fa-terminal", iconOptions(p), p.className)}/>
export const ThumbTack = (p) => <i className={classnames("fa fa-thumb-tack", iconOptions(p), p.className)}/>
export const ThumbsDown = (p) => <i className={classnames("fa fa-thumbs-down", iconOptions(p), p.className)}/>
export const ThumbsODown = (p) => <i className={classnames("fa fa-thumbs-o-down", iconOptions(p), p.className)}/>
export const ThumbsOUp = (p) => <i className={classnames("fa fa-thumbs-o-up", iconOptions(p), p.className)}/>
export const ThumbsUp = (p) => <i className={classnames("fa fa-thumbs-up", iconOptions(p), p.className)}/>
export const Ticket = (p) => <i className={classnames("fa fa-ticket", iconOptions(p), p.className)}/>
export const Times = (p) => <i className={classnames("fa fa-times", iconOptions(p), p.className)}/>
export const TimesCircle = (p) => <i className={classnames("fa fa-times-circle", iconOptions(p), p.className)}/>
export const TimesCircleO = (p) => <i className={classnames("fa fa-times-circle-o", iconOptions(p), p.className)}/>
export const Tint = (p) => <i className={classnames("fa fa-tint", iconOptions(p), p.className)}/>
export const ToggleDown = (p) => <i className={classnames("fa fa-toggle-down", iconOptions(p), p.className)}/>
export const ToggleLeft = (p) => <i className={classnames("fa fa-toggle-left", iconOptions(p), p.className)}/>
export const ToggleOff = (p) => <i className={classnames("fa fa-toggle-off", iconOptions(p), p.className)}/>
export const ToggleOn = (p) => <i className={classnames("fa fa-toggle-on", iconOptions(p), p.className)}/>
export const ToggleRight = (p) => <i className={classnames("fa fa-toggle-right", iconOptions(p), p.className)}/>
export const ToggleUp = (p) => <i className={classnames("fa fa-toggle-up", iconOptions(p), p.className)}/>
export const Trademark = (p) => <i className={classnames("fa fa-trademark", iconOptions(p), p.className)}/>
export const Trash = (p) => <i className={classnames("fa fa-trash", iconOptions(p), p.className)}/>
export const TrashO = (p) => <i className={classnames("fa fa-trash-o", iconOptions(p), p.className)}/>
export const Tree = (p) => <i className={classnames("fa fa-tree", iconOptions(p), p.className)}/>
export const Trophy = (p) => <i className={classnames("fa fa-trophy", iconOptions(p), p.className)}/>
export const Truck = (p) => <i className={classnames("fa fa-truck", iconOptions(p), p.className)}/>
export const Tty = (p) => <i className={classnames("fa fa-tty", iconOptions(p), p.className)}/>
export const Tv = (p) => <i className={classnames("fa fa-tv", iconOptions(p), p.className)}/>
export const Umbrella = (p) => <i className={classnames("fa fa-umbrella", iconOptions(p), p.className)}/>
export const University = (p) => <i className={classnames("fa fa-university", iconOptions(p), p.className)}/>
export const Unlock = (p) => <i className={classnames("fa fa-unlock", iconOptions(p), p.className)}/>
export const UnlockAlt = (p) => <i className={classnames("fa fa-unlock-alt", iconOptions(p), p.className)}/>
export const Unsorted = (p) => <i className={classnames("fa fa-unsorted", iconOptions(p), p.className)}/>
export const Upload = (p) => <i className={classnames("fa fa-upload", iconOptions(p), p.className)}/>
export const User = (p) => <i className={classnames("fa fa-user", iconOptions(p), p.className)}/>
export const UserPlus = (p) => <i className={classnames("fa fa-user-plus", iconOptions(p), p.className)}/>
export const UserLock = (p) => <i className={classnames("fa fa-user-lock", iconOptions(p), p.className)}/>
export const UserSecret = (p) => <i className={classnames("fa fa-user-secret", iconOptions(p), p.className)}/>
export const UserTimes = (p) => <i className={classnames("fa fa-user-times", iconOptions(p), p.className)}/>
export const Users = (p) => <i className={classnames("fa fa-users", iconOptions(p), p.className)}/>
export const VideoCamera = (p) => <i className={classnames("fa fa-video-camera", iconOptions(p), p.className)}/>
export const VolumeControlPhone = (p) => <i className={classnames("fa fa-volume-control-phone", iconOptions(p), p.className)}/>
export const VolumeDown = (p) => <i className={classnames("fa fa-volume-down", iconOptions(p), p.className)}/>
export const VolumeOff = (p) => <i className={classnames("fa fa-volume-off", iconOptions(p), p.className)}/>
export const VolumeUp = (p) => <i className={classnames("fa fa-volume-up", iconOptions(p), p.className)}/>
export const Warning = (p) => <i className={classnames("fa fa-warning", iconOptions(p), p.className)}/>
export const Wheelchair = (p) => <i className={classnames("fa fa-wheelchair", iconOptions(p), p.className)}/>
export const WheelchairAlt = (p) => <i className={classnames("fa fa-wheelchair-alt", iconOptions(p), p.className)}/>
export const Wifi = (p) => <i className={classnames("fa fa-wifi", iconOptions(p), p.className)}/>
export const Wrench = (p) => <i className={classnames("fa fa-wrench", iconOptions(p), p.className)}/>
export const HandODown = (p) => <i className={classnames("fa fa-hand-o-down", iconOptions(p), p.className)}/>
export const HandOLeft = (p) => <i className={classnames("fa fa-hand-o-left", iconOptions(p), p.className)}/>
export const HandORight = (p) => <i className={classnames("fa fa-hand-o-right", iconOptions(p), p.className)}/>
export const HandOUp = (p) => <i className={classnames("fa fa-hand-o-up", iconOptions(p), p.className)}/>
export const Ambulance = (p) => <i className={classnames("fa fa-ambulance", iconOptions(p), p.className)}/>
export const Subway = (p) => <i className={classnames("fa fa-subway", iconOptions(p), p.className)}/>
export const Train = (p) => <i className={classnames("fa fa-train", iconOptions(p), p.className)}/>
export const Genderless = (p) => <i className={classnames("fa fa-genderless", iconOptions(p), p.className)}/>
export const Intersex = (p) => <i className={classnames("fa fa-intersex", iconOptions(p), p.className)}/>
export const Mars = (p) => <i className={classnames("fa fa-mars", iconOptions(p), p.className)}/>
export const MarsDouble = (p) => <i className={classnames("fa fa-mars-double", iconOptions(p), p.className)}/>
export const MarsStroke = (p) => <i className={classnames("fa fa-mars-stroke", iconOptions(p), p.className)}/>
export const MarsStrokeH = (p) => <i className={classnames("fa fa-mars-stroke-h", iconOptions(p), p.className)}/>
export const MarsStrokeV = (p) => <i className={classnames("fa fa-mars-stroke-v", iconOptions(p), p.className)}/>
export const Mercury = (p) => <i className={classnames("fa fa-mercury", iconOptions(p), p.className)}/>
export const Neuter = (p) => <i className={classnames("fa fa-neuter", iconOptions(p), p.className)}/>
export const Transgender = (p) => <i className={classnames("fa fa-transgender", iconOptions(p), p.className)}/>
export const TransgenderAlt = (p) => <i className={classnames("fa fa-transgender-alt", iconOptions(p), p.className)}/>
export const Venus = (p) => <i className={classnames("fa fa-venus", iconOptions(p), p.className)}/>
export const VenusDouble = (p) => <i className={classnames("fa fa-venus-double", iconOptions(p), p.className)}/>
export const VenusMars = (p) => <i className={classnames("fa fa-venus-mars", iconOptions(p), p.className)}/>
export const File = (p) => <i className={classnames("fa fa-file", iconOptions(p), p.className)}/>
export const FileO = (p) => <i className={classnames("fa fa-file-o", iconOptions(p), p.className)}/>
export const FileText = (p) => <i className={classnames("fa fa-file-text", iconOptions(p), p.className)}/>
export const FileTextO = (p) => <i className={classnames("fa fa-file-text-o", iconOptions(p), p.className)}/>
export const CcAmex = (p) => <i className={classnames("fa fa-cc-amex", iconOptions(p), p.className)}/>
export const CcDinersClub = (p) => <i className={classnames("fa fa-cc-diners-club", iconOptions(p), p.className)}/>
export const CcDiscover = (p) => <i className={classnames("fa fa-cc-discover", iconOptions(p), p.className)}/>
export const CcJcb = (p) => <i className={classnames("fa fa-cc-jcb", iconOptions(p), p.className)}/>
export const CcMastercard = (p) => <i className={classnames("fa fa-cc-mastercard", iconOptions(p), p.className)}/>
export const CcPaypal = (p) => <i className={classnames("fa fa-cc-paypal", iconOptions(p), p.className)}/>
export const CcStripe = (p) => <i className={classnames("fa fa-cc-stripe", iconOptions(p), p.className)}/>
export const CcVisa = (p) => <i className={classnames("fa fa-cc-visa", iconOptions(p), p.className)}/>
export const GoogleWallet = (p) => <i className={classnames("fa fa-google-wallet", iconOptions(p), p.className)}/>
export const Paypal = (p) => <i className={classnames("fa fa-paypal", iconOptions(p), p.className)}/>
export const Bitcoin = (p) => <i className={classnames("fa fa-bitcoin", iconOptions(p), p.className)}/>
export const Btc = (p) => <i className={classnames("fa fa-btc", iconOptions(p), p.className)}/>
export const Cny = (p) => <i className={classnames("fa fa-cny", iconOptions(p), p.className)}/>
export const Dollar = (p) => <i className={classnames("fa fa-dollar", iconOptions(p), p.className)}/>
export const Eur = (p) => <i className={classnames("fa fa-eur", iconOptions(p), p.className)}/>
export const Euro = (p) => <i className={classnames("fa fa-euro", iconOptions(p), p.className)}/>
export const Gbp = (p) => <i className={classnames("fa fa-gbp", iconOptions(p), p.className)}/>
export const Gg = (p) => <i className={classnames("fa fa-gg", iconOptions(p), p.className)}/>
export const GgCircle = (p) => <i className={classnames("fa fa-gg-circle", iconOptions(p), p.className)}/>
export const Ils = (p) => <i className={classnames("fa fa-ils", iconOptions(p), p.className)}/>
export const Inr = (p) => <i className={classnames("fa fa-inr", iconOptions(p), p.className)}/>
export const Jpy = (p) => <i className={classnames("fa fa-jpy", iconOptions(p), p.className)}/>
export const Krw = (p) => <i className={classnames("fa fa-krw", iconOptions(p), p.className)}/>
export const Rmb = (p) => <i className={classnames("fa fa-rmb", iconOptions(p), p.className)}/>
export const Rouble = (p) => <i className={classnames("fa fa-rouble", iconOptions(p), p.className)}/>
export const Rub = (p) => <i className={classnames("fa fa-rub", iconOptions(p), p.className)}/>
export const Ruble = (p) => <i className={classnames("fa fa-ruble", iconOptions(p), p.className)}/>
export const Rupee = (p) => <i className={classnames("fa fa-rupee", iconOptions(p), p.className)}/>
export const Shekel = (p) => <i className={classnames("fa fa-shekel", iconOptions(p), p.className)}/>
export const Sheqel = (p) => <i className={classnames("fa fa-sheqel", iconOptions(p), p.className)}/>
export const Try = (p) => <i className={classnames("fa fa-try", iconOptions(p), p.className)}/>
export const TurkishLira = (p) => <i className={classnames("fa fa-turkish-lira", iconOptions(p), p.className)}/>
export const Usd = (p) => <i className={classnames("fa fa-usd", iconOptions(p), p.className)}/>
export const Viacoin = (p) => <i className={classnames("fa fa-viacoin", iconOptions(p), p.className)}/>
export const Won = (p) => <i className={classnames("fa fa-won", iconOptions(p), p.className)}/>
export const Yen = (p) => <i className={classnames("fa fa-yen", iconOptions(p), p.className)}/>
export const AlignCenter = (p) => <i className={classnames("fa fa-align-center", iconOptions(p), p.className)}/>
export const AlignJustify = (p) => <i className={classnames("fa fa-align-justify", iconOptions(p), p.className)}/>
export const AlignLeft = (p) => <i className={classnames("fa fa-align-left", iconOptions(p), p.className)}/>
export const AlignRight = (p) => <i className={classnames("fa fa-align-right", iconOptions(p), p.className)}/>
export const Bold = (p) => <i className={classnames("fa fa-bold", iconOptions(p), p.className)}/>
export const Chain = (p) => <i className={classnames("fa fa-chain", iconOptions(p), p.className)}/>
export const ChainBroken = (p) => <i className={classnames("fa fa-chain-broken", iconOptions(p), p.className)}/>
export const Clipboard = (p) => <i className={classnames("fa fa-clipboard", iconOptions(p), p.className)}/>
export const Columns = (p) => <i className={classnames("fa fa-columns", iconOptions(p), p.className)}/>
export const Copy = (p) => <i className={classnames("fa fa-copy", iconOptions(p), p.className)}/>
export const Cut = (p) => <i className={classnames("fa fa-cut", iconOptions(p), p.className)}/>
export const Dedent = (p) => <i className={classnames("fa fa-dedent", iconOptions(p), p.className)}/>
export const FilesO = (p) => <i className={classnames("fa fa-files-o", iconOptions(p), p.className)}/>
export const FloppyO = (p) => <i className={classnames("fa fa-floppy-o", iconOptions(p), p.className)}/>
export const Font = (p) => <i className={classnames("fa fa-font", iconOptions(p), p.className)}/>
export const Header = (p) => <i className={classnames("fa fa-header", iconOptions(p), p.className)}/>
export const Indent = (p) => <i className={classnames("fa fa-indent", iconOptions(p), p.className)}/>
export const Italic = (p) => <i className={classnames("fa fa-italic", iconOptions(p), p.className)}/>
export const Link = (p) => <i className={classnames("fa fa-link", iconOptions(p), p.className)}/>
export const List = (p) => <i className={classnames("fa fa-list", iconOptions(p), p.className)}/>
export const ListAlt = (p) => <i className={classnames("fa fa-list-alt", iconOptions(p), p.className)}/>
export const ListOl = (p) => <i className={classnames("fa fa-list-ol", iconOptions(p), p.className)}/>
export const ListUl = (p) => <i className={classnames("fa fa-list-ul", iconOptions(p), p.className)}/>
export const Outdent = (p) => <i className={classnames("fa fa-outdent", iconOptions(p), p.className)}/>
export const Paperclip = (p) => <i className={classnames("fa fa-paperclip", iconOptions(p), p.className)}/>
export const Paragraph = (p) => <i className={classnames("fa fa-paragraph", iconOptions(p), p.className)}/>
export const Paste = (p) => <i className={classnames("fa fa-paste", iconOptions(p), p.className)}/>
export const Repeat = (p) => <i className={classnames("fa fa-repeat", iconOptions(p), p.className)}/>
export const RotateLeft = (p) => <i className={classnames("fa fa-rotate-left", iconOptions(p), p.className)}/>
export const RotateRight = (p) => <i className={classnames("fa fa-rotate-right", iconOptions(p), p.className)}/>
export const Save = (p) => <i className={classnames("fa fa-save", iconOptions(p), p.className)}/>
export const Scissors = (p) => <i className={classnames("fa fa-scissors", iconOptions(p), p.className)}/>
export const Strikethrough = (p) => <i className={classnames("fa fa-strikethrough", iconOptions(p), p.className)}/>
export const Subscript = (p) => <i className={classnames("fa fa-subscript", iconOptions(p), p.className)}/>
export const Superscript = (p) => <i className={classnames("fa fa-superscript", iconOptions(p), p.className)}/>
export const Table = (p) => <i className={classnames("fa fa-table", iconOptions(p), p.className)}/>
export const TextHeight = (p) => <i className={classnames("fa fa-text-height", iconOptions(p), p.className)}/>
export const TextWidth = (p) => <i className={classnames("fa fa-text-width", iconOptions(p), p.className)}/>
export const Th = (p) => <i className={classnames("fa fa-th", iconOptions(p), p.className)}/>
export const ThLarge = (p) => <i className={classnames("fa fa-th-large", iconOptions(p), p.className)}/>
export const ThList = (p) => <i className={classnames("fa fa-th-list", iconOptions(p), p.className)}/>
export const Underline = (p) => <i className={classnames("fa fa-underline", iconOptions(p), p.className)}/>
export const Undo = (p) => <i className={classnames("fa fa-undo", iconOptions(p), p.className)}/>
export const Unlink = (p) => <i className={classnames("fa fa-unlink", iconOptions(p), p.className)}/>
export const AngleDoubleDown = (p) => <i className={classnames("fa fa-angle-double-down", iconOptions(p), p.className)}/>
export const AngleDoubleLeft = (p) => <i className={classnames("fa fa-angle-double-left", iconOptions(p), p.className)}/>
export const AngleDoubleRight = (p) => <i className={classnames("fa fa-angle-double-right", iconOptions(p), p.className)}/>
export const AngleDoubleUp = (p) => <i className={classnames("fa fa-angle-double-up", iconOptions(p), p.className)}/>
export const AngleDown = (p) => <i className={classnames("fa fa-angle-down", iconOptions(p), p.className)}/>
export const AngleLeft = (p) => <i className={classnames("fa fa-angle-left", iconOptions(p), p.className)}/>
export const AngleRight = (p) => <i className={classnames("fa fa-angle-right", iconOptions(p), p.className)}/>
export const AngleUp = (p) => <i className={classnames("fa fa-angle-up", iconOptions(p), p.className)}/>
export const ArrowCircleDown = (p) => <i className={classnames("fa fa-arrow-circle-down", iconOptions(p), p.className)}/>
export const ArrowCircleLeft = (p) => <i className={classnames("fa fa-arrow-circle-left", iconOptions(p), p.className)}/>
export const ArrowCircleODown = (p) => <i className={classnames("fa fa-arrow-circle-o-down", iconOptions(p), p.className)}/>
export const ArrowCircleOLeft = (p) => <i className={classnames("fa fa-arrow-circle-o-left", iconOptions(p), p.className)}/>
export const ArrowCircleORight = (p) => <i className={classnames("fa fa-arrow-circle-o-right", iconOptions(p), p.className)}/>
export const ArrowCircleOUp = (p) => <i className={classnames("fa fa-arrow-circle-o-up", iconOptions(p), p.className)}/>
export const ArrowCircleRight = (p) => <i className={classnames("fa fa-arrow-circle-right", iconOptions(p), p.className)}/>
export const ArrowCircleUp = (p) => <i className={classnames("fa fa-arrow-circle-up", iconOptions(p), p.className)}/>
export const ArrowDown = (p) => <i className={classnames("fa fa-arrow-down", iconOptions(p), p.className)}/>
export const ArrowLeft = (p) => <i className={classnames("fa fa-arrow-left", iconOptions(p), p.className)}/>
export const ArrowRight = (p) => <i className={classnames("fa fa-arrow-right", iconOptions(p), p.className)}/>
export const ArrowUp = (p) => <i className={classnames("fa fa-arrow-up", iconOptions(p), p.className)}/>
export const ArrowsAlt = (p) => <i className={classnames("fa fa-arrows-alt", iconOptions(p), p.className)}/>
export const CaretLeft = (p) => <i className={classnames("fa fa-caret-left", iconOptions(p), p.className)}/>
export const CaretRight = (p) => <i className={classnames("fa fa-caret-right", iconOptions(p), p.className)}/>
export const CaretUp = (p) => <i className={classnames("fa fa-caret-up", iconOptions(p), p.className)}/>
export const ChevronCircleDown = (p) => <i className={classnames("fa fa-chevron-circle-down", iconOptions(p), p.className)}/>
export const ChevronCircleLeft = (p) => <i className={classnames("fa fa-chevron-circle-left", iconOptions(p), p.className)}/>
export const ChevronCircleRight = (p) => <i className={classnames("fa fa-chevron-circle-right", iconOptions(p), p.className)}/>
export const ChevronCircleUp = (p) => <i className={classnames("fa fa-chevron-circle-up", iconOptions(p), p.className)}/>
export const ChevronDown = (p) => <i className={classnames("fa fa-chevron-down", iconOptions(p), p.className)}/>
export const ChevronLeft = (p) => <i className={classnames("fa fa-chevron-left", iconOptions(p), p.className)}/>
export const ChevronRight = (p) => <i className={classnames("fa fa-chevron-right", iconOptions(p), p.className)}/>
export const ChevronUp = (p) => <i className={classnames("fa fa-chevron-up", iconOptions(p), p.className)}/>
export const LongArrowDown = (p) => <i className={classnames("fa fa-long-arrow-down", iconOptions(p), p.className)}/>
export const LongArrowLeft = (p) => <i className={classnames("fa fa-long-arrow-left", iconOptions(p), p.className)}/>
export const LongArrowRight = (p) => <i className={classnames("fa fa-long-arrow-right", iconOptions(p), p.className)}/>
export const LongArrowUp = (p) => <i className={classnames("fa fa-long-arrow-up", iconOptions(p), p.className)}/>
export const Backward = (p) => <i className={classnames("fa fa-backward", iconOptions(p), p.className)}/>
export const Compress = (p) => <i className={classnames("fa fa-compress", iconOptions(p), p.className)}/>
export const Eject = (p) => <i className={classnames("fa fa-eject", iconOptions(p), p.className)}/>
export const Expand = (p) => <i className={classnames("fa fa-expand", iconOptions(p), p.className)}/>
export const FastBackward = (p) => <i className={classnames("fa fa-fast-backward", iconOptions(p), p.className)}/>
export const FastForward = (p) => <i className={classnames("fa fa-fast-forward", iconOptions(p), p.className)}/>
export const Forward = (p) => <i className={classnames("fa fa-forward", iconOptions(p), p.className)}/>
export const Pause = (p) => <i className={classnames("fa fa-pause", iconOptions(p), p.className)}/>
export const PauseCircle = (p) => <i className={classnames("fa fa-pause-circle", iconOptions(p), p.className)}/>
export const PauseCircleO = (p) => <i className={classnames("fa fa-pause-circle-o", iconOptions(p), p.className)}/>
export const Play = (p) => <i className={classnames("fa fa-play", iconOptions(p), p.className)}/>
export const PlayCircle = (p) => <i className={classnames("fa fa-play-circle", iconOptions(p), p.className)}/>
export const PlayCircleO = (p) => <i className={classnames("fa fa-play-circle-o", iconOptions(p), p.className)}/>
export const StepBackward = (p) => <i className={classnames("fa fa-step-backward", iconOptions(p), p.className)}/>
export const StepForward = (p) => <i className={classnames("fa fa-step-forward", iconOptions(p), p.className)}/>
export const Stop = (p) => <i className={classnames("fa fa-stop", iconOptions(p), p.className)}/>
export const StopCircle = (p) => <i className={classnames("fa fa-stop-circle", iconOptions(p), p.className)}/>
export const StopCircleO = (p) => <i className={classnames("fa fa-stop-circle-o", iconOptions(p), p.className)}/>
export const YoutubePlay = (p) => <i className={classnames("fa fa-youtube-play", iconOptions(p), p.className)}/>
export const Adn = (p) => <i className={classnames("fa fa-adn", iconOptions(p), p.className)}/>
export const Amazon = (p) => <i className={classnames("fa fa-amazon", iconOptions(p), p.className)}/>
export const Android = (p) => <i className={classnames("fa fa-android", iconOptions(p), p.className)}/>
export const Angellist = (p) => <i className={classnames("fa fa-angellist", iconOptions(p), p.className)}/>
export const Apple = (p) => <i className={classnames("fa fa-apple", iconOptions(p), p.className)}/>
export const Behance = (p) => <i className={classnames("fa fa-behance", iconOptions(p), p.className)}/>
export const BehanceSquare = (p) => <i className={classnames("fa fa-behance-square", iconOptions(p), p.className)}/>
export const Bitbucket = (p) => <i className={classnames("fa fa-bitbucket", iconOptions(p), p.className)}/>
export const BitbucketSquare = (p) => <i className={classnames("fa fa-bitbucket-square", iconOptions(p), p.className)}/>
export const BlackTie = (p) => <i className={classnames("fa fa-black-tie", iconOptions(p), p.className)}/>
export const Buysellads = (p) => <i className={classnames("fa fa-buysellads", iconOptions(p), p.className)}/>
export const Chrome = (p) => <i className={classnames("fa fa-chrome", iconOptions(p), p.className)}/>
export const Codepen = (p) => <i className={classnames("fa fa-codepen", iconOptions(p), p.className)}/>
export const Codiepie = (p) => <i className={classnames("fa fa-codiepie", iconOptions(p), p.className)}/>
export const Connectdevelop = (p) => <i className={classnames("fa fa-connectdevelop", iconOptions(p), p.className)}/>
export const Contao = (p) => <i className={classnames("fa fa-contao", iconOptions(p), p.className)}/>
export const Css3 = (p) => <i className={classnames("fa fa-css3", iconOptions(p), p.className)}/>
export const Dashcube = (p) => <i className={classnames("fa fa-dashcube", iconOptions(p), p.className)}/>
export const Delicious = (p) => <i className={classnames("fa fa-delicious", iconOptions(p), p.className)}/>
export const Deviantart = (p) => <i className={classnames("fa fa-deviantart", iconOptions(p), p.className)}/>
export const Digg = (p) => <i className={classnames("fa fa-digg", iconOptions(p), p.className)}/>
export const Dribbble = (p) => <i className={classnames("fa fa-dribbble", iconOptions(p), p.className)}/>
export const Dropbox = (p) => <i className={classnames("fa fa-dropbox", iconOptions(p), p.className)}/>
export const Drupal = (p) => <i className={classnames("fa fa-drupal", iconOptions(p), p.className)}/>
export const Edge = (p) => <i className={classnames("fa fa-edge", iconOptions(p), p.className)}/>
export const Empire = (p) => <i className={classnames("fa fa-empire", iconOptions(p), p.className)}/>
export const Envira = (p) => <i className={classnames("fa fa-envira", iconOptions(p), p.className)}/>
export const Expeditedssl = (p) => <i className={classnames("fa fa-expeditedssl", iconOptions(p), p.className)}/>
export const Fa = (p) => <i className={classnames("fa fa-fa", iconOptions(p), p.className)}/>
export const Facebook = (p) => <i className={classnames("fa fa-facebook", iconOptions(p), p.className)}/>
export const FacebookF = (p) => <i className={classnames("fa fa-facebook-f", iconOptions(p), p.className)}/>
export const FacebookOfficial = (p) => <i className={classnames("fa fa-facebook-official", iconOptions(p), p.className)}/>
export const FacebookSquare = (p) => <i className={classnames("fa fa-facebook-square", iconOptions(p), p.className)}/>
export const Firefox = (p) => <i className={classnames("fa fa-firefox", iconOptions(p), p.className)}/>
export const FirstOrder = (p) => <i className={classnames("fa fa-first-order", iconOptions(p), p.className)}/>
export const Flickr = (p) => <i className={classnames("fa fa-flickr", iconOptions(p), p.className)}/>
export const Fonticons = (p) => <i className={classnames("fa fa-fonticons", iconOptions(p), p.className)}/>
export const FortAwesome = (p) => <i className={classnames("fa fa-fort-awesome", iconOptions(p), p.className)}/>
export const Forumbee = (p) => <i className={classnames("fa fa-forumbee", iconOptions(p), p.className)}/>
export const Foursquare = (p) => <i className={classnames("fa fa-foursquare", iconOptions(p), p.className)}/>
export const Ge = (p) => <i className={classnames("fa fa-ge", iconOptions(p), p.className)}/>
export const GetPocket = (p) => <i className={classnames("fa fa-get-pocket", iconOptions(p), p.className)}/>
export const Git = (p) => <i className={classnames("fa fa-git", iconOptions(p), p.className)}/>
export const GitSquare = (p) => <i className={classnames("fa fa-git-square", iconOptions(p), p.className)}/>
export const Github = (p) => <i className={classnames("fa fa-github", iconOptions(p), p.className)}/>
export const GithubAlt = (p) => <i className={classnames("fa fa-github-alt", iconOptions(p), p.className)}/>
export const GithubSquare = (p) => <i className={classnames("fa fa-github-square", iconOptions(p), p.className)}/>
export const Gitlab = (p) => <i className={classnames("fa fa-gitlab", iconOptions(p), p.className)}/>
export const Gittip = (p) => <i className={classnames("fa fa-gittip", iconOptions(p), p.className)}/>
export const Glide = (p) => <i className={classnames("fa fa-glide", iconOptions(p), p.className)}/>
export const GlideG = (p) => <i className={classnames("fa fa-glide-g", iconOptions(p), p.className)}/>
export const Google = (p) => <i className={classnames("fa fa-google", iconOptions(p), p.className)}/>
export const GooglePlus = (p) => <i className={classnames("fa fa-google-plus", iconOptions(p), p.className)}/>
export const GooglePlusCircle = (p) => <i className={classnames("fa fa-google-plus-circle", iconOptions(p), p.className)}/>
export const GooglePlusOfficial = (p) => <i className={classnames("fa fa-google-plus-official", iconOptions(p), p.className)}/>
export const GooglePlusSquare = (p) => <i className={classnames("fa fa-google-plus-square", iconOptions(p), p.className)}/>
export const Gratipay = (p) => <i className={classnames("fa fa-gratipay", iconOptions(p), p.className)}/>
export const HackerNews = (p) => <i className={classnames("fa fa-hacker-news", iconOptions(p), p.className)}/>
export const Houzz = (p) => <i className={classnames("fa fa-houzz", iconOptions(p), p.className)}/>
export const Html5 = (p) => <i className={classnames("fa fa-html5", iconOptions(p), p.className)}/>
export const Instagram = (p) => <i className={classnames("fa fa-instagram", iconOptions(p), p.className)}/>
export const InternetExplorer = (p) => <i className={classnames("fa fa-internet-explorer", iconOptions(p), p.className)}/>
export const Ioxhost = (p) => <i className={classnames("fa fa-ioxhost", iconOptions(p), p.className)}/>
export const Joomla = (p) => <i className={classnames("fa fa-joomla", iconOptions(p), p.className)}/>
export const Jsfiddle = (p) => <i className={classnames("fa fa-jsfiddle", iconOptions(p), p.className)}/>
export const Lastfm = (p) => <i className={classnames("fa fa-lastfm", iconOptions(p), p.className)}/>
export const LastfmSquare = (p) => <i className={classnames("fa fa-lastfm-square", iconOptions(p), p.className)}/>
export const Leanpub = (p) => <i className={classnames("fa fa-leanpub", iconOptions(p), p.className)}/>
export const Linkedin = (p) => <i className={classnames("fa fa-linkedin", iconOptions(p), p.className)}/>
export const LinkedinSquare = (p) => <i className={classnames("fa fa-linkedin-square", iconOptions(p), p.className)}/>
export const Linux = (p) => <i className={classnames("fa fa-linux", iconOptions(p), p.className)}/>
export const Maxcdn = (p) => <i className={classnames("fa fa-maxcdn", iconOptions(p), p.className)}/>
export const Meanpath = (p) => <i className={classnames("fa fa-meanpath", iconOptions(p), p.className)}/>
export const Medium = (p) => <i className={classnames("fa fa-medium", iconOptions(p), p.className)}/>
export const Mixcloud = (p) => <i className={classnames("fa fa-mixcloud", iconOptions(p), p.className)}/>
export const Modx = (p) => <i className={classnames("fa fa-modx", iconOptions(p), p.className)}/>
export const Odnoklassniki = (p) => <i className={classnames("fa fa-odnoklassniki", iconOptions(p), p.className)}/>
export const OdnoklassnikiSquare = (p) => <i className={classnames("fa fa-odnoklassniki-square", iconOptions(p), p.className)}/>
export const Opencart = (p) => <i className={classnames("fa fa-opencart", iconOptions(p), p.className)}/>
export const Openid = (p) => <i className={classnames("fa fa-openid", iconOptions(p), p.className)}/>
export const Opera = (p) => <i className={classnames("fa fa-opera", iconOptions(p), p.className)}/>
export const OptinMonster = (p) => <i className={classnames("fa fa-optin-monster", iconOptions(p), p.className)}/>
export const Pagelines = (p) => <i className={classnames("fa fa-pagelines", iconOptions(p), p.className)}/>
export const PiedPiper = (p) => <i className={classnames("fa fa-pied-piper", iconOptions(p), p.className)}/>
export const PiedPiperAlt = (p) => <i className={classnames("fa fa-pied-piper-alt", iconOptions(p), p.className)}/>
export const PiedPiperPp = (p) => <i className={classnames("fa fa-pied-piper-pp", iconOptions(p), p.className)}/>
export const Pinterest = (p) => <i className={classnames("fa fa-pinterest", iconOptions(p), p.className)}/>
export const PinterestP = (p) => <i className={classnames("fa fa-pinterest-p", iconOptions(p), p.className)}/>
export const PinterestSquare = (p) => <i className={classnames("fa fa-pinterest-square", iconOptions(p), p.className)}/>
export const ProductHunt = (p) => <i className={classnames("fa fa-product-hunt", iconOptions(p), p.className)}/>
export const Qq = (p) => <i className={classnames("fa fa-qq", iconOptions(p), p.className)}/>
export const Ra = (p) => <i className={classnames("fa fa-ra", iconOptions(p), p.className)}/>
export const Rebel = (p) => <i className={classnames("fa fa-rebel", iconOptions(p), p.className)}/>
export const Reddit = (p) => <i className={classnames("fa fa-reddit", iconOptions(p), p.className)}/>
export const RedditAlien = (p) => <i className={classnames("fa fa-reddit-alien", iconOptions(p), p.className)}/>
export const RedditSquare = (p) => <i className={classnames("fa fa-reddit-square", iconOptions(p), p.className)}/>
export const Renren = (p) => <i className={classnames("fa fa-renren", iconOptions(p), p.className)}/>
export const Resistance = (p) => <i className={classnames("fa fa-resistance", iconOptions(p), p.className)}/>
export const Safari = (p) => <i className={classnames("fa fa-safari", iconOptions(p), p.className)}/>
export const Scribd = (p) => <i className={classnames("fa fa-scribd", iconOptions(p), p.className)}/>
export const Sellsy = (p) => <i className={classnames("fa fa-sellsy", iconOptions(p), p.className)}/>
export const Shirtsinbulk = (p) => <i className={classnames("fa fa-shirtsinbulk", iconOptions(p), p.className)}/>
export const Simplybuilt = (p) => <i className={classnames("fa fa-simplybuilt", iconOptions(p), p.className)}/>
export const Skyatlas = (p) => <i className={classnames("fa fa-skyatlas", iconOptions(p), p.className)}/>
export const Skype = (p) => <i className={classnames("fa fa-skype", iconOptions(p), p.className)}/>
export const Slack = (p) => <i className={classnames("fa fa-slack", iconOptions(p), p.className)}/>
export const Slideshare = (p) => <i className={classnames("fa fa-slideshare", iconOptions(p), p.className)}/>
export const Snapchat = (p) => <i className={classnames("fa fa-snapchat", iconOptions(p), p.className)}/>
export const SnapchatGhost = (p) => <i className={classnames("fa fa-snapchat-ghost", iconOptions(p), p.className)}/>
export const SnapchatSquare = (p) => <i className={classnames("fa fa-snapchat-square", iconOptions(p), p.className)}/>
export const Soundcloud = (p) => <i className={classnames("fa fa-soundcloud", iconOptions(p), p.className)}/>
export const Spotify = (p) => <i className={classnames("fa fa-spotify", iconOptions(p), p.className)}/>
export const StackExchange = (p) => <i className={classnames("fa fa-stack-exchange", iconOptions(p), p.className)}/>
export const StackOverflow = (p) => <i className={classnames("fa fa-stack-overflow", iconOptions(p), p.className)}/>
export const Steam = (p) => <i className={classnames("fa fa-steam", iconOptions(p), p.className)}/>
export const SteamSquare = (p) => <i className={classnames("fa fa-steam-square", iconOptions(p), p.className)}/>
export const Stumbleupon = (p) => <i className={classnames("fa fa-stumbleupon", iconOptions(p), p.className)}/>
export const StumbleuponCircle = (p) => <i className={classnames("fa fa-stumbleupon-circle", iconOptions(p), p.className)}/>
export const TencentWeibo = (p) => <i className={classnames("fa fa-tencent-weibo", iconOptions(p), p.className)}/>
export const Themeisle = (p) => <i className={classnames("fa fa-themeisle", iconOptions(p), p.className)}/>
export const Trello = (p) => <i className={classnames("fa fa-trello", iconOptions(p), p.className)}/>
export const Tripadvisor = (p) => <i className={classnames("fa fa-tripadvisor", iconOptions(p), p.className)}/>
export const Tumblr = (p) => <i className={classnames("fa fa-tumblr", iconOptions(p), p.className)}/>
export const TumblrSquare = (p) => <i className={classnames("fa fa-tumblr-square", iconOptions(p), p.className)}/>
export const Twitch = (p) => <i className={classnames("fa fa-twitch", iconOptions(p), p.className)}/>
export const Twitter = (p) => <i className={classnames("fa fa-twitter", iconOptions(p), p.className)}/>
export const TwitterSquare = (p) => <i className={classnames("fa fa-twitter-square", iconOptions(p), p.className)}/>
export const Usb = (p) => <i className={classnames("fa fa-usb", iconOptions(p), p.className)}/>
export const Viadeo = (p) => <i className={classnames("fa fa-viadeo", iconOptions(p), p.className)}/>
export const ViadeoSquare = (p) => <i className={classnames("fa fa-viadeo-square", iconOptions(p), p.className)}/>
export const Vimeo = (p) => <i className={classnames("fa fa-vimeo", iconOptions(p), p.className)}/>
export const VimeoSquare = (p) => <i className={classnames("fa fa-vimeo-square", iconOptions(p), p.className)}/>
export const Vine = (p) => <i className={classnames("fa fa-vine", iconOptions(p), p.className)}/>
export const Vk = (p) => <i className={classnames("fa fa-vk", iconOptions(p), p.className)}/>
export const Wechat = (p) => <i className={classnames("fa fa-wechat", iconOptions(p), p.className)}/>
export const Weibo = (p) => <i className={classnames("fa fa-weibo", iconOptions(p), p.className)}/>
export const Weixin = (p) => <i className={classnames("fa fa-weixin", iconOptions(p), p.className)}/>
export const Whatsapp = (p) => <i className={classnames("fa fa-whatsapp", iconOptions(p), p.className)}/>
export const WikipediaW = (p) => <i className={classnames("fa fa-wikipedia-w", iconOptions(p), p.className)}/>
export const Windows = (p) => <i className={classnames("fa fa-windows", iconOptions(p), p.className)}/>
export const Wordpress = (p) => <i className={classnames("fa fa-wordpress", iconOptions(p), p.className)}/>
export const Wpbeginner = (p) => <i className={classnames("fa fa-wpbeginner", iconOptions(p), p.className)}/>
export const Wpforms = (p) => <i className={classnames("fa fa-wpforms", iconOptions(p), p.className)}/>
export const Xing = (p) => <i className={classnames("fa fa-xing", iconOptions(p), p.className)}/>
export const XingSquare = (p) => <i className={classnames("fa fa-xing-square", iconOptions(p), p.className)}/>
export const YCombinator = (p) => <i className={classnames("fa fa-y-combinator", iconOptions(p), p.className)}/>
export const YCombinatorSquare = (p) => <i className={classnames("fa fa-y-combinator-square", iconOptions(p), p.className)}/>
export const Yahoo = (p) => <i className={classnames("fa fa-yahoo", iconOptions(p), p.className)}/>
export const Yc = (p) => <i className={classnames("fa fa-yc", iconOptions(p), p.className)}/>
export const YcSquare = (p) => <i className={classnames("fa fa-yc-square", iconOptions(p), p.className)}/>
export const Yelp = (p) => <i className={classnames("fa fa-yelp", iconOptions(p), p.className)}/>
export const Yoast = (p) => <i className={classnames("fa fa-yoast", iconOptions(p), p.className)}/>
export const Youtube = (p) => <i className={classnames("fa fa-youtube", iconOptions(p), p.className)}/>
export const YoutubeSquare = (p) => <i className={classnames("fa fa-youtube-square", iconOptions(p), p.className)}/>
export const HSquare = (p) => <i className={classnames("fa fa-h-square", iconOptions(p), p.className)}/>
export const HospitalO = (p) => <i className={classnames("fa fa-hospital-o", iconOptions(p), p.className)}/>
export const Medkit = (p) => <i className={classnames("fa fa-medkit", iconOptions(p), p.className)}/>
export const Stethoscope = (p) => <i className={classnames("fa fa-stethoscope", iconOptions(p), p.className)}/>
export const UserMd = (p) => <i className={classnames("fa fa-user-md", iconOptions(p), p.className)}/>

export const FaStack = (p) => <span className={classnames("fa-stack", iconOptions(p), p.className)}>{p.children}</span>
export const FaUl = (p) => <ul className={classnames("fa-ul", p.className)}>{p.children}</ul>
